### ISSUE TITLE
Deep-linking past the access.r.c paywall

### ISSUE THREAD

**Issue by gerdesas** [CentOS/docs#9]
Chapter 26 contains a link that deep-links past the access.redhat.com paywall to https://access.redhat.com/labs/rhelupgradehelper/ which doesn't look kosher.

**Comment by quaid** [comment]
Caveat:  All the URLs in this document may not have been tested. In particular, I personally had not done a log in test.

To test I just did the following:

1. Clicked on the link https://access.redhat.com/labs/rhelupgradehelper/
2. Was told I needed an account, so I created a 'Personal' account. (I used truthful information & identified it as a test account.)
3. Once I completed the account creation, I was redirected to the original link.

That means we have some options, these are the ones that come to mind for me:

- Remove all the URLs that require a login to use.
-- This bit of surgery will require attention for each location to patch the content.
- Add an admonition (Note) that the link(s) require a user account and login that can be created by the user, and that the entire thing is not affiliated with the CentOS Project as it's a third-party knowledge resource.

@gerdesas et al -- Any other ideas?

I'm fine personally with the "keep links & inform about an account required", I think that might be the most useful for users.

**Comment by gerdesas** [comment]
Dump the entire section.  The update tool does _not_ work.

**Comment by quaid** [comment]
OK, we'll trim out the section on upgrade tool. That's what issue #10 is about, right?

For this issue, I was also thinking in general about what to do about other deep-links.

**Comment by gerdesas** [comment]
My opinion is that in an install document nothing should be linked past
the pay-wall.  Asking content consumers to register merely to install
seems a grave disservice and an undue burden placed on them.

**Comment by quaid** [comment]
Link is removed and chapter content is updated as per issue #10

**Comment by pbokoc** [comment]
The whole upgrading chapter was removed in #12. See https://github.com/CentOS/docs/issues/10#issuecomment-407790323 for details.
